version: '3'


vars:
  path:
    sh: uv run python tools setting circuit_python_drive_location
  board_id: 'waveshare_rp2040_one'


interval: 500ms


tasks:
  .install:
    internal: true
    cmds:
      - uv run circup --path '{{ .path }}' install --requirement requirements.txt
      - uv run circuitpython_setboard {{ .board_id }}

  install:
    desc: Install dependencies.
    cmds:
      - task: enable_drive
      - task: .install

  dist:
    desc: Package the firmware for distribution.
    vars:
      temp_dir: dist
    cmds:
      - mkdir -pv {{ .temp_dir }}
      - touch {{ .temp_dir }}/boot_out.txt
      - cp boot_out.txt {{ .temp_dir }}/
      - task: .install
        vars:
          path: "{{ .temp_dir }}"
      - cp -vr src/* {{ .temp_dir }}/
      - mv {{ .temp_dir }}/main.py {{ .temp_dir }}/code.py
      - rm -rv {{ .temp_dir }}/boot_out.txt

  upload:
    desc: Upload firmware to the board.
    deps:
      - enable_drive
    sources:
      - 'src/**/*'
    generates:
      - '{{ .patth }}/**/*'
    cmds:
      - task: install
      - cp -vr src/* '{{ .path }}'
      - mv '{{ .path }}/main.py' '{{ .path }}/code.py'

  enable_drive:
    desc: Temporarily enable the drive, to allow uploading firmware.
    status:
      - test -d {{ .path }}
    cmds:
      - uv run python tools enable_drive
      - while ! test -d '{{ .path }}'; do sleep .1; done

  lint:
    desc: Run linters.
    cmds:
      - uv run ruff check --fix src tests

  test:
    desc: Run tests.
    cmds:
      - task: lint
      - rm -rv reports/ .coverage || true
      - uv run pytest tests