version: '3'

vars:
  path: 'E:\\'
  board_id: nice_nano

interval: 500ms

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv run circup --path '{{ .path }}' install --requirement requirements.txt
      - uv run circuitpython_setboard {{ .board_id }}

  upload:
    desc: Upload source
    deps:
      - install
    sources:
      - '*.py'g
      - 'lib/**/*'
    cmds:
      - cp -vr *.py lib/ {{ .path }}
