name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install task
        uses: go-task/setup-task@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: task test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: reports/junit_test_report.xml
          show: all
        if: always()

      - name: Coverage Report
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: ./reports/unit/unit.xml
          coverage-path: ./reports/coverage/coverage.xml
        if: always()

      - name: Upload reports
        uses: actions/upload-artifact@v6
        with:
          name: snesctl-firmware
          path: .pio/build/nicenano/firmware.*
        if: always()
