name: test


on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install task
        uses: go-task/setup-task@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Test
        run: task test

      - name: Test Report
        uses: dorny/test-reporter@v2
        with:
          name: Mouse Jiggler Tests
          path: reports/junit_test_report.xml
          reporter: python-xunit
        if: always()

      - name: Update badges
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: c2389bbe0a2312450ec9358e81f1b0e8
          token: ${{ secrets.GIST_TOKEN }}

      - name: Upload reports
        uses: actions/upload-artifact@v6
        with:
          name: mouse-jiggler-reports
          path: reports/
        if: always()